const orders = [
  {
    id: 1,
    name: "Npath",
    max_bid_price: 4188,
    data_package_type: "Device Location",
  },
  {
    id: 2,
    name: "Avaveo",
    max_bid_price: 241,
    data_package_type: "Device Behaviour",
  },
  { id: 3, name: "Tazz", max_bid_price: 7178, data_package_type: "ID Mapping" },
  {
    id: 4,
    name: "Yodoo",
    max_bid_price: 4877,
    data_package_type: "Device Behaviour",
  },
  {
    id: 5,
    name: "Babbleblab",
    max_bid_price: 2888,
    data_package_type: "Device Location",
  },
  {
    id: 6,
    name: "Twitterwire",
    max_bid_price: 7353,
    data_package_type: "Device Behaviour",
  },
  {
    id: 7,
    name: "Realmix",
    max_bid_price: 6372,
    data_package_type: "ID Mapping",
  },
  {
    id: 8,
    name: "Bubblemix",
    max_bid_price: 434,
    data_package_type: "Device Location",
  },
  {
    id: 9,
    name: "Dabjam",
    max_bid_price: 2296,
    data_package_type: "Device Behaviour",
  },
  {
    id: 10,
    name: "Yodel",
    max_bid_price: 7688,
    data_package_type: "Device Location",
  },
  {
    id: 11,
    name: "Dynava",
    max_bid_price: 728,
    data_package_type: "Device Location",
  },
  {
    id: 12,
    name: "Jetpulse",
    max_bid_price: 3265,
    data_package_type: "ID Mapping",
  },
  {
    id: 13,
    name: "Devpoint",
    max_bid_price: 4512,
    data_package_type: "Device Behaviour",
  },
  {
    id: 14,
    name: "Podcat",
    max_bid_price: 8781,
    data_package_type: "Device Location",
  },
  {
    id: 15,
    name: "Oba",
    max_bid_price: 8503,
    data_package_type: "Device Location",
  },
  {
    id: 16,
    name: "Yadel",
    max_bid_price: 2437,
    data_package_type: "Device Behaviour",
  },
  {
    id: 17,
    name: "Oyoyo",
    max_bid_price: 2922,
    data_package_type: "Device Behaviour",
  },
  {
    id: 18,
    name: "Blogspan",
    max_bid_price: 629,
    data_package_type: "Device Location",
  },
  {
    id: 19,
    name: "Avavee",
    max_bid_price: 4122,
    data_package_type: "Device Behaviour",
  },
  {
    id: 20,
    name: "Flashspan",
    max_bid_price: 1099,
    data_package_type: "ID Mapping",
  },
  {
    id: 21,
    name: "Trudeo",
    max_bid_price: 2503,
    data_package_type: "Device Behaviour",
  },
  {
    id: 22,
    name: "Voonder",
    max_bid_price: 4733,
    data_package_type: "Device Location",
  },
  {
    id: 23,
    name: "Lazz",
    max_bid_price: 7339,
    data_package_type: "Device Location",
  },
  {
    id: 24,
    name: "Wikivu",
    max_bid_price: 8171,
    data_package_type: "ID Mapping",
  },
  {
    id: 25,
    name: "Demimbu",
    max_bid_price: 1883,
    data_package_type: "Device Behaviour",
  },
  {
    id: 26,
    name: "Browsetype",
    max_bid_price: 8947,
    data_package_type: "Device Behaviour",
  },
  {
    id: 27,
    name: "Eadel",
    max_bid_price: 1717,
    data_package_type: "Device Location",
  },
  {
    id: 28,
    name: "Jabbersphere",
    max_bid_price: 8644,
    data_package_type: "Device Behaviour",
  },
  {
    id: 29,
    name: "Rhyloo",
    max_bid_price: 6211,
    data_package_type: "Device Location",
  },
  {
    id: 30,
    name: "Oodoo",
    max_bid_price: 5885,
    data_package_type: "ID Mapping",
  },
  // {
  //   id: 31,
  //   name: "Trudoo",
  //   max_bid_price: 2368,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 32,
  //   name: "Oyoloo",
  //   max_bid_price: 8023,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 33,
  //   name: "Jabberstorm",
  //   max_bid_price: 3986,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 34,
  //   name: "Voomm",
  //   max_bid_price: 2323,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 35,
  //   name: "Oloo",
  //   max_bid_price: 1402,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 36,
  //   name: "Gabvine",
  //   max_bid_price: 9581,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 37,
  //   name: "Shuffletag",
  //   max_bid_price: 4183,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 38,
  //   name: "Realpoint",
  //   max_bid_price: 1550,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 39,
  //   name: "Topdrive",
  //   max_bid_price: 7896,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 40,
  //   name: "Chatterpoint",
  //   max_bid_price: 6151,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 41,
  //   name: "Tekfly",
  //   max_bid_price: 3024,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 42,
  //   name: "Kimia",
  //   max_bid_price: 2718,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 43,
  //   name: "Skyba",
  //   max_bid_price: 2739,
  //   data_package_type: "ID Mapping",
  // },
  // {
  //   id: 44,
  //   name: "Mycat",
  //   max_bid_price: 9216,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 45,
  //   name: "Fivebridge",
  //   max_bid_price: 6322,
  //   data_package_type: "Device Location",
  // },
  // {
  //   id: 46,
  //   name: "Geba",
  //   max_bid_price: 4011,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 47,
  //   name: "Wordify",
  //   max_bid_price: 7719,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 48,
  //   name: "Photobug",
  //   max_bid_price: 2263,
  //   data_package_type: "Device Location",
  // },
  // {
  //   id: 49,
  //   name: "Vitz",
  //   max_bid_price: 652,
  //   data_package_type: "Device Behaviour",
  // },
  // {
  //   id: 50,
  //   name: "Yamia",
  //   max_bid_price: 4291,
  //   data_package_type: "ID Mapping",
  // },
];

export default orders;
